ccflags-y += -I$(srctree)

oplus_bsp_frame_boost-y := \
        frame_boost.o \
        frame_sysctl.o \
        frame_info.o \
        frame_group.o \
        cluster_boost.o \
        frame_debug.o \
        frame_timer.o

obj-$(CONFIG_OPLUS_FEATURE_FRAME_BOOST) += oplus_bsp_frame_boost.o
