# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_OPLUS_FEATURE_SCHED_ASSIST) += sched_assist/
obj-$(CONFIG_OPLUS_FEATURE_OPROJECT) += projectinfo/
obj-$(CONFIG_OPLUS_FEATURE_PHOENIX) += phoenix/
obj-$(CONFIG_OPLUS_DEVICE_IFNO) += device_info/
obj-$(CONFIG_OPLUS_FEATURE_MIDAS_V2) += midas/
obj-$(CONFIG_OPLUS_FEATURE_OCH) += cpufreq_health/
obj-$(CONFIG_OPLUS_FEATURE_FRAME_BOOST) += frame_boost/

obj-$(CONFIG_EVONIX_OPLUS_HEALTHINFO_LITE) += healthinfo_lite/

obj-$(CONFIG_OPLUS_FEATURE_WAKER_IDENTIFY) += waker_identify/
