obj-$(CONFIG_DUMP_TASKS_MEM) += dump_tasks_mem/
obj-$(CONFIG_OPLUS_FEATURE_SIGKILL_DIAGNOSIS) += sigkill_diagnosis/
obj-$(CONFIG_PROCESS_RECLAIM_ENHANCE) += process_reclaim/
obj-$(CONFIG_OPLUS_FEATURE_KSWAPD_OPT) += kswapd_opt/
obj-$(CONFIG_OPLUS_FEATURE_PROACTIVE_COMPACT) += proactive_compact/
